# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Entertainment_Among_Us' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Entertainment_Among_Us

  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Alamofire', '~> 5.5'
  pod 'SnapKit', '~> 5.6.0'
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'SideMenu'
  pod 'Socket.IO-Client-Swift', '~> 16.0.0'
  pod 'Alamofire'
end
