# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'withoutStroyBoard_Entertainment_AmongUs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for withoutStroyBoard_Entertainment_AmongUs

  pod 'Toast-Swift', '~> 5.0.1'
  pod 'SideMenu'
  pod 'Alamofire', '~> 5.5'

end
