# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'WaittingRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaittingRoom
  pod 'SideMenu'
  pod 'Socket.IO-Client-Swift', '~> 16.0.0'
  pod 'Alamofire'
  pod 'AlertsAndPickers'
  pod 'TextFieldEffects'

end