# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WaittingRoom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WaittingRoom
  pod 'Socket.IO-Client-Swift', '~> 16.0.0'

end
